### ISSUE TITLE
Query by subject, does not work

### ISSUE THREAD

**Issue by lidanqing123** [mjs/imapclient#406] opened 2020-07-16 14:25 UTC
I query by subject and it doesn't work
```
        self.server.select_folder('INBOX', readonly=True)
        messages = self.server.search(['SUBJECT', 'final QA',  'TO', 'lidanqing@xx.com'])
```
However, many of the subject in the query results do not contain "final QA"

**Comment by mjs** [comment] 2020-07-19 10:13
I've just manually verified that searching by subject works for me with v2.1.0. The problem is likely to be with the server implementation of the search. Do you know what the server is?

Could you double check the subjects of the messages being returned by the server with something like this to make sure that they really don't match:

```python
msgs = server.search(...)    # fill in your search here
for m in server.fetch(msgs, ['RFC822.HEADER']).values(): 
     print(list(x for x in m[b'RFC822.HEADER'].splitlines() if x.startswith(b'Subject'))[0])
```

It would also be useful to turn on debug logging before the search call and post the output here. This is described here: https://imapclient.readthedocs.io/en/2.1.0/concepts.html#logging

**Comment by mjs** [comment] 2020-09-18 09:11
Closing this as the issue is likely to be specific to a particular IMAP server. Feel free to reopen if you feel there's a problem with IMAPClient that we need to look at.

**Closed by mjs** 2020-09-18 09:11 UTC
