### ISSUE TITLE
Certificate mismatch issue Mac, Python3, IMAPClient 1.1.0

### ISSUE THREAD

**Issue by paul-hammant** [mjs/imapclient#326] opened 2017-12-27 19:59 UTC
```
from imapclient import IMAPClient
server = IMAPClient('imap-mail.outlook.com', port=993, use_uid=True, ssl=True)
```

Barfs like so:

```
$ python3 foo.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/imapclient/tls.py", line 151, in wrap_socket
    newsock = ssl_context.wrap_socket(sock, server_hostname=hostname)
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 676, in wrap_socket
    self.check_hostname)
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 241, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 263, in do_handshake
    match_hostname(self.getpeercert(), self._conn.get_servername().decode('utf-8'))
  File "/usr/local/lib/python3.6/site-packages/backports/ssl/core.py", line 184, in match_hostname
    % (hostname, dnsnames[0]))
backports.ssl.core.CertificateError: hostname 'imap-mail.outlook.com' doesn't match 'outlook.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 2, in <module>
    server = IMAPClient('imap-mail.outlook.com', port=993, use_uid=True, ssl=True)
  File "/usr/local/lib/python3.6/site-packages/imapclient/imapclient.py", line 161, in __init__
    self._imap = self._create_IMAP4()
  File "/usr/local/lib/python3.6/site-packages/imapclient/imapclient.py", line 173, in _create_IMAP4
    self._timeout)
  File "/usr/local/lib/python3.6/site-packages/imapclient/tls.py", line 171, in __init__
    imaplib.IMAP4.__init__(self, host, port)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imaplib.py", line 197, in __init__
    self.open(host, port)
  File "/usr/local/lib/python3.6/site-packages/imapclient/tls.py", line 177, in open
    self.sock = wrap_socket(sock, self.ssl_context, host)
  File "/usr/local/lib/python3.6/site-packages/imapclient/tls.py", line 154, in wrap_socket
    raise imaplib.IMAP4.error("certificate error for %s: %s" % (hostname, str(err)))
imaplib.error: certificate error for imap-mail.outlook.com: hostname 'imap-mail.outlook.com' doesn't match 'outlook.com'
```

Other pertinent facts:

* MacOS: 10.13.2
* OpenSSL version: LibreSSL 2.2.7
* Python version: 3.6.4
* $ pip3 freeze | grep crypto == 2.1.3
* $ pip3 freeze | grep IMAPClient == 1.1.0
* $ pip3 freeze | grep backports.ssl == 0.0.9

**Comment by NicolasLM** [comment] 2017-12-28 08:59
Hi, I believe this is already fixed on `master`. Can you try with the latest commit?

**Comment by paul-hammant** [comment] 2017-12-28 17:46
Sure.

**Comment by paul-hammant** [comment] 2017-12-28 18:10
Appears to work:

```
class TestOutlookDotComInterop(unittest.TestCase):

    def setUp(self):
        super(TestOutlookDotComInterop, self).setUp()

    def test_connect(self):
        from imapclient import IMAPClient
        server = IMAPClient('imap-mail.outlook.com', port=993, use_uid=True, ssl=True)
        print("server= " + str(server))
        server.shutdown()
```

Both for Python 2.7.14 and 3.6.3 on the Mac.  I can't check Windows presently, nor Linux.

**Comment by NicolasLM** [comment] 2017-12-29 08:31
Great, closing the issue then. We will try to release those fixes in `IMAPClient 2.0` ASAP.

**Closed by NicolasLM** 2017-12-29 08:31 UTC

**Comment by PythonSmonkey** [comment] 2018-01-11 04:36
I still got the incompatibility output. Any module need to be installed or any setting need to be input? 

from imapclient import IMAPClient
server = IMAPClient('imap.gmail.com', port=993, use_uid=True, ssl=True)

Other pertinent facts:
* MacOS: 10.13.2
* OpenSSL version: pyOpenSSL==17.5.0
* Python version: 3.6.4
* $ pip3 freeze | grep cryptography == 2.1.4
* $ pip3 freeze | grep IMAPClient == 1.1.0
* $ pip3 freeze | grep backports.ssl == 0.0.9

$ pip3 freeze
asn1crypto==0.24.0
backports.ssl==0.0.9
beautifulsoup4==4.6.0
certifi==2017.7.27.1
cffi==1.11.2
chardet==3.0.4
cryptography==2.1.4
et-xmlfile==1.0.1
icrawler==0.4.7
idna==2.6
IMAPClient==1.1.0
jdcal==1.3
lxml==4.1.0
olefile==0.44
openpyxl==2.4.9
Pillow==4.3.0
pycparser==2.18
pygame==1.9.3
pyOpenSSL==17.5.0
PyPDF2==1.26.0
pyperclip==1.5.27
python-docx==0.8.6
pyzmail36==1.0.3
requests==2.18.4
selenium==3.6.0
six==1.11.0
urllib3==1.22

**Comment by NicolasLM** [comment] 2018-01-11 07:46
@PythonSmonkey, as said in this thread, the problem is fixed on `master`. Since you have IMAPClient 1.1.0 installed, you do not run the fixed code.

@mjs is anything blocking the release at this point?

**Comment by mjs** [comment] 2018-01-11 11:05
I just need to finalise the release notes and then it's going out.

**Comment by PythonSmonkey** [comment] 2018-01-11 12:50
Unbelievable I got response so quickly, many many thanks!  Actually I have gotten stuck here for two days. Now I know my direction and will learn how to run the fixed code. Again, thanks a lot!

**Comment by paul-hammant** [comment] 2018-01-11 16:12
I've been stuck for a year on this :-P  I can finally abandon Python2 now, and am very excited :)
