### ISSUE TITLE
Python 3.9 incompatible with Imapclient due to new  timeout parameter in imaplib

### ISSUE THREAD

**Issue by tomanizer** [mjs/imapclient#442] opened 2021-05-12 12:07 UTC
Using Imapclient in Python 3.9 raises on connect.

TypeError: open() takes 3 positional arguments but 4 were given. 

This appears to be related to 
https://docs.python.org/3/library/imaplib.html
Changed in version 3.9: The optional timeout parameter was added.

The error does not occur in Python <= 3.8.

**Comment by NicolasLM** [comment] 2021-05-12 12:10
Duplicate of #425

**Closed by NicolasLM** 2021-05-12 12:10 UTC

**Comment by tomanizer** [comment] 2021-05-12 13:06
Thank you for pointing that out @NicolasLM

On further investigation, I noticed that conda installs old version 2.0.0 which still has the bug, whereas 2.2.0 on pypi has it fixed.

`conda install imapaclient`
https://anaconda.org/conda-forge/imapclient

Does version 2.2.0 need a new conda package and upload to anaconda  repo and conda forge?

**Comment by mjs** [comment] 2021-07-28 10:05
It would see that a newer conda package is required. I have no idea what the process is for that however as @NicolasLM and I don't have anything to do with the conda package.
